name: add-to-project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add to project
    # Don't run on forks cause they don't have the token set
    # This means that any outside branch that is PR'd (which is the vast majority) won't get auto added to board
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: "https://github.com/orgs/R2Northstar/projects/3"
          github-token: "${{ secrets.PROJECT_BOARD_TOKEN }}"
          
